server:
  port: 8004

spring:
  application:
    name: payment-provider-service
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}