server:
  port: 8003

spring:
  application:
    name: payment-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.28.170.49:3306/db01?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 123456
  cloud:
    zookeeper:
      connect-string: 129.28.170.49:2181