server:
  port: 80

spring:
  application:
    name: payment-consumer-service-04
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}